#Defining a function to plot the frequency generated by a model and observed frequency 
#This function is written by Daniel Meier and Jürg Schelldorfer, in the code corresponding to the article 
#"Insights from Inside Neural Networks". 
#The original code can be found here: https://github.com/JSchelldorfer/ActuarialDataScience/tree/master/2%20-%20Insights%20from%20Inside%20Neural%20Networks

plot_freq <- function(test, xvar, title, model, mdlvariant) {
  out <- test %>% group_by(!!sym(xvar)) %>%
    summarize(obs = sum(NClaims) / sum(Expo), pred = sum(!!sym(mdlvariant)) / sum(Expo))
  
  ggplot(out, aes(x = !!sym(xvar), group = 1)) +
    geom_point(aes(y = pred, colour = model)) +
    geom_point(aes(y = obs, colour = "observed")) + 
    geom_line(aes(y = pred, colour = model), linetype = "dashed") +
    geom_line(aes(y = obs, colour = "observed"), linetype = "dashed") +
    ylim(0, 0.35) + labs(x = xvar, y = "frequency", title = title) +
    theme(legend.position = "bottom")
}
